# Generated by Django 5.2.1 on 2025-05-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.TextField(verbose_name='Descrição da tarefa')),
                ('pontos', models.PositiveIntegerField(verbose_name='Pontuação')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('tipo', models.CharField(default='d', max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
