# Generated by Django 5.2.1 on 2025-05-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points_of_change_2', '0003_novo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='tipo',
            field=models.CharField(default='Avulsa', max_length=20),
        ),
    ]
