# Generated by Django 5.2.1 on 2025-05-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points_of_change_2', '0005_alter_tarefa_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novo_tipo',
            name='nome',
            field=models.TextField(default='Avulso', verbose_name='Descrição da lista'),
        ),
    ]
