# Generated by Django 5.2.1 on 2025-05-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points_of_change_2', '0006_alter_novo_tipo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novo_tipo',
            name='meta',
            field=models.PositiveIntegerField(default='0', verbose_name='Meta'),
        ),
    ]
