# Generated by Django 5.2.1 on 2025-05-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points_of_change_2', '0007_alter_novo_tipo_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('data_publicacao', models.DateField()),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(max_length=50)),
                ('nome_postador', models.CharField(max_length=100)),
                ('cargo_postador', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='recomendacoes_pdfs/')),
            ],
        ),
    ]
