# Generated by Django 5.2.1 on 2025-05-20 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points_of_change_2', '0009_voto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voto',
        ),
    ]
